package tech.lenooby09.offlineAuth.atproto

import java.security.KeyPair
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * A pending pairing — generated by `/bluesky` and consumed by the browser-side
 * handle entry form. Bound to a specific Minecraft player UUID so the OAuth
 * callback knows which in-game session to authenticate.
 */
data class PendingPairing(
	val playerUuid: UUID,
	val createdAt: Long = System.currentTimeMillis(),
)

/**
 * In-flight ATProto OAuth state created at PAR submit time. The atproto
 * `state` parameter is the key; the callback consumes the row by its `state`
 * query param to recover the DPoP key, code verifier, and target token
 * endpoint.
 */
data class PendingAtprotoAuth(
	val pairingToken: String,
	val codeVerifier: String,
	val dpopKeyPair: KeyPair,
	val authServerIssuer: String,
	val tokenEndpoint: String,
	val pdsUrl: String,
	val handle: String,
	val did: String,
	val createdAt: Long = System.currentTimeMillis(),
)

/**
 * In-memory two-map store with TTL cleanup on every insert. Mirrors
 * `intermediate-oauth/store/SessionStore.kt` but with offline-auth-specific
 * pairing semantics.
 */
class BlueskySessionStore(
	private val pairingTokenTtlMs: Long = 10 * 60 * 1000L,
) {
	private val pendingByPairingToken = ConcurrentHashMap<String, PendingPairing>()
	private val pendingByAtprotoState = ConcurrentHashMap<String, PendingAtprotoAuth>()

	fun storePairing(pairingToken: String, pairing: PendingPairing) {
		cleanup()
		pendingByPairingToken[pairingToken] = pairing
	}

	/** Read-only lookup; the entry is consumed when the OAuth callback completes. */
	fun getPairing(pairingToken: String): PendingPairing? {
		val entry = pendingByPairingToken[pairingToken] ?: return null
		if (System.currentTimeMillis() - entry.createdAt > pairingTokenTtlMs) {
			pendingByPairingToken.remove(pairingToken)
			return null
		}
		return entry
	}

	fun consumePairing(pairingToken: String): PendingPairing? = pendingByPairingToken.remove(pairingToken)

	fun storeAtprotoAuth(atprotoState: String, auth: PendingAtprotoAuth) {
		cleanup()
		pendingByAtprotoState[atprotoState] = auth
	}

	fun consumeAtprotoAuth(atprotoState: String): PendingAtprotoAuth? = pendingByAtprotoState.remove(atprotoState)

	/**
	 * Drop all pending entries belonging to a player UUID — used when a player
	 * disconnects so they cannot re-authenticate later via a previously-issued
	 * pairing token.
	 */
	fun voidByPlayer(playerUuid: UUID) {
		pendingByPairingToken.entries.removeIf { it.value.playerUuid == playerUuid }
		pendingByAtprotoState.entries.removeIf {
			val token = it.value.pairingToken
			pendingByPairingToken[token]?.playerUuid == playerUuid
		}
	}

	private fun cleanup() {
		val now = System.currentTimeMillis()
		pendingByPairingToken.entries.removeIf { now - it.value.createdAt > pairingTokenTtlMs }
		pendingByAtprotoState.entries.removeIf { now - it.value.createdAt > pairingTokenTtlMs }
	}
}
